Fekide/strapi-plugin-translate

- __mocks__/contentTypes.js
- server/utils/__tests__/translate-relations.test.js
- server/utils/translate-relations.js
fixes #4 
This fixes localizations being removed after translating an entity.
The reason for this happening is that localizations are stored as relation in the schema, and are being removed by the `translateRelations` method
> Fix: localizations are removed after translating

- README.md
- package.json
- server/utils/__tests__/deepl-api.test.js
- server/utils/byte-length.js
- server/utils/chunks.js
- server/utils/constants.js
- server/utils/deepl-api.js
- yarn.lock
improve the splitting of text into chunks by having three options
- append text to current chunk
- add text to new chunk if
- more than 50 texts in the chunk (was possible before)
- chunks byte size is too large (new feature)
- split text into multiple texts if it is itself larger than the request size
(new feature but not necessarily safe for content layout)
fixes #8
> fix: 413 Error when fields are too large

- package.json
When installing `strapi-plugin-deepl`, npm emits a warning:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'strapi-plugin-deepl@0.3.8',
npm WARN EBADENGINE   required: { node: '>=12.x. <=16.x.x', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.18.0', npm: '8.19.2' }
npm WARN EBADENGINE }
```
The problem is the dot in `>=12.x.`. Removing `.x.` and `.x.x` completely should be fully equivalent.
> Fix `npm` warnings about incompatible engine versions

- README.md
- plugin/README.md
- plugin/__mocks__/components.js
- plugin/__mocks__/initSetup.js
- plugin/package.json
- plugin/server/config/__tests__/config.test.js
- plugin/server/config/index.js
- plugin/server/services/__tests__/format-service.test.js
- plugin/server/services/__tests__/translate-service.test.js
- plugin/server/services/format.js
- plugin/server/services/index.js
- plugin/server/services/translate.js
- plugin/server/utils/__tests__/translatable-fields.test.js
- plugin/server/utils/delete-fields.js
- plugin/server/utils/translatable-fields.js
- plugin/server/utils/translated-field-types.js
- providers/deepl/__mocks__/initStrapi.js
- providers/deepl/lib/__tests__/deepl.test.js
- providers/deepl/lib/index.js
- yarn.lock
Since some providers do not handle Markdown or HTML out of the box, this feature enables the configuration and handling of different text formats. There are 3 different formats defined: plain,
markdown and html.
On translation fields are grouped by their format and submitted per format to the provider.
Providers can either translate the text in the respective format or optionally parse them to a format supported by them. There is a new service defined, that allows the parsing between html and markdown.
BREAKING CHANGE: Translate service api requires array of objects of shape {field:string,format:string} instead of just the field as string
fix #25
> feat: handle format of text field types

- plugin/package.json
I got this error:
```
Error: Plugin name "Translate" is not in kebab (an-example-of-kebab-case)
at validatePluginName (/Users/strapi/node_modules/@strapi/strapi/lib/core/loaders/plugins/get-enabled-plugins.js:21:11)
```
Seems that the name should be lower case:
> 3\. Choose "plugin" from the list, press Enter, and give the plugin a name in kebab-case (e.g. my-plugin)
https://docs.strapi.io/developer-docs/latest/development/plugins-development.html#create-a-plugin
See check in https://github.com/strapi/strapi/blob/141f89f81f4a18766b5c5c0c545daf79e2760ede/packages/core/strapi/lib/core/loaders/plugins/get-enabled-plugins.js#L19
> Make strapi name lowercase

- .github/dependabot.yml
- providers/deepl/README.md
- providers/deepl/lib/__tests__/parse-locale.test.js
- providers/deepl/lib/index.js
- providers/deepl/lib/parse-locale.js
- providers/deepl/package.json
The 'EN' and 'PT' locale are deprecated in favor of the more specific versions. This feature fixes
the issue and allows more customization so not everyone needs to use EN-US for the EN locale
fix https://github.com/Fekide/strapi-plugin-translate/issues/62
> feat(provider-deepl): support custom locale mapping

- plugin/server/utils/__tests__/translatable-fields.test.js
- plugin/server/utils/translatable-fields.js
When installing the plugin, the pluginOptions are not yet set for each content-type. This only happens once a content-type is updated. With this fix that is not necessary anymore.
fix #66
> fix(configuration): do not require translate pluginOptions

- providers/deepl/lib/__tests__/parse-locale.test.js
- providers/deepl/lib/index.js
- providers/deepl/lib/parse-locale.js
The source language in DeepL does not accept the country codes in translation
fix #73
> fix(provider-deepl): make parsed source local not include country

- playground/config/plugins.js
- playground/package.json
- yarn.lock
The plugin versions in the playground always had to be updated, which is tedious and prone to errors. Now the version is always the one in the repository as it is directly referenced. Also after some short testing it also had no problems anymore with the dev dependencies on strapi packages in the plugin or providers.
> chore(playground): remove explicit dependency on plugin in playground

- plugin/admin/src/components/CMEditViewTranslateLocale/index.js
- plugin/package.json
- yarn.lock
The axiosInstance was replaced with useFetchClient in strapi@4.6.1. However since using the useFetchClient would require to put a dependency on @strapi/helper-plugin@^4.6.0, we are using the simpler request utility. The fetchClient is also not necessary as we do not require caching behavior.
fix #121
> fix(admin): replace axiosInstance with request from @strapi/helper-plugin

- plugin/admin/src/components/CMEditViewTranslateLocale/utils/parse-relations.js
> fix(parse-relations): return empty array if the relation is empty

- plugin/admin/src/components/Usage/index.js
strapi v4.8 seems to throw error if Td element is not direct child of Tr element.
There was a React Fragment, which is now replaced by an array of Td elements.
fix #142
> fix(admin): fix error with strapi v4.8

- plugin/server/utils/__tests__/translate-relations.test.js
- plugin/server/utils/translate-relations.js
When the pluginOptions for translating relations are not set or set empty, the relation was not translated correctly. This should fix the default behavior to be translation.
fix #161
> fix(relations): make default behavior translations

- playground/cypress/e2e/batch-translation.cy.js
- playground/cypress/e2e/direct-translation.cy.js
- playground/cypress/support/commands.js
- playground/data/data.json
- playground/package.json
- playground/src/api/article/content-types/article/schema.json
- playground/src/api/categories-page/content-types/categories-page/schema.json
- playground/src/api/categories-page/controllers/categories-page.js
- playground/src/api/categories-page/routes/categories-page.js
- playground/src/api/categories-page/services/categories-page.js
- playground/src/api/category/content-types/category/schema.json
- playground/src/bootstrap.js
- playground/src/components/shared/category.json
- playground/templates/template.package.json
- plugin/admin/src/components/CMEditViewTranslateLocale/utils/parse-relations.js
- plugin/admin/src/components/Collection/CollectionRow.js
- yarn.lock
When translating relations in a component, the relation is not translated and when clicking on the
relation field an error is thrown. The bug was that the relation parsing did not handle repeated
components correctly. Another connected issue was that after translating, all fields in the repeated
components were opening simultaneously, which was caused by a missing __temp_key__.
fix https://github.com/Fekide/strapi-plugin-translate/issues/152
>  fix(direct-translation): issue with translating relations in components 

- plugin/admin/src/components/Collection/CollectionTable.js
- plugin/admin/src/pages/HomePage/index.js
This PRs refactor's `Box` component to a `Layout` inside `CollectionTable.js`, so we can have proper overflow in the table, when we have multiple locales supported.
| Before  | After |
| ------------- | ------------- |
| <img src="https://github.com/Fekide/strapi-plugin-translate/assets/12672541/919061c5-a26e-4084-b492-1ecb1adf1364"/>  | <img src="https://github.com/Fekide/strapi-plugin-translate/assets/12672541/4c0433ac-1de4-4520-b0a9-d80eedf36028"/>  |
Also removed redundant div, and replace with fragment.
> fix: enable table overflow-x

- plugin/admin/src/components/CMEditViewTranslateLocale/index.js
Previously, when a JSON field was present, the the field would fail to update and the tab would hang. this should now be fixed
re #246
I'm not entirely sure whether this addresses the main problem with #246, but it fixes a problem I encountered while looking into this.
> fix(single-translation): fix issue with JSON fields breaking the translation process

- plugin/server/services/batch-translate/BatchTranslateJob.js
service create uses a different naming scheme for single types, so switching to entityService
> fix(batch-translate): translation of single types

- playground/cypress/e2e/batch-translation.cy.js
- playground/cypress/e2e/direct-translation.cy.js
addresses https://github.com/Fekide/strapi-plugin-translate/issues/367
based on https://github.com/Fekide/strapi-plugin-translate/pull/359
- fix cy.get(id) query failing since strapi started using ids starting and ending with the ":" character
- fix failing to select the correct locale from the dropdown due to different DOM structure of select component
> 367 bug e2e tests fail with 359

- plugin/admin/src/pages/App/index.js
The NotFound component was removed in @strapi/helper-plugin and was not actually used
fix #339
> fix(admin): remove NotFound component

- .github/workflows/e2e.yml
- .github/workflows/unittest.yml
- playground/.gitignore
- playground/cypress/e2e/batch-translation.cy.js
- playground/cypress/e2e/direct-translation.cy.js
- playground/package.json
- playground/src/bootstrap.js
- playground/src/helpers/init-admin.js
- playground/templates/template.package.json
- plugin/package.json
- providers/deepl/package.json
- providers/libretranslate/package.json
- yarn.lock
With Strapi v4.13 support for nodejs 20 was introduced and with v4.15 support for nodejs 16 was dropped. This plugin should support the most versions possible.
The e2e tests currently fail for multiple reasons, especially since direct translation currently only works after reloading the page. That is however mostly a strapi issue. Batch translation tests should be updated.
fix #357
> fix(deps): support node 20 and strapi v4.13

- providers/deepl/lib/constants.js
- providers/deepl/lib/index.js
A requirement/advisory from the DeepL nodejs documentation: [deepl-node#writing-a-plugin](https://github.com/DeepLcom/deepl-node/tree/main#writing-a-plugin)
> fix(provider-deepl): add appInfo to DeepL Translator options

- playground/cypress/e2e/direct-translation.cy.js
- playground/data/data.json
- playground/src/api/article/content-types/article/schema.json
- playground/src/api/homepage/content-types/homepage/schema.json
- playground/src/api/writer/content-types/writer/schema.json
- playground/src/components/sections/hero.json
- playground/src/components/shared/content.json
- plugin/admin/src/components/CMEditViewTranslateLocale/index.js
- plugin/admin/src/components/CMEditViewTranslateLocale/utils/flattenEntity.js
- plugin/admin/src/components/CMEditViewTranslateLocale/utils/parse-relations.js
This pull request includes multiple changes across various files to enhance the translation and dynamic content features. The most important changes are grouped by their themes below:
* [`plugin/admin/src/components/CMEditViewTranslateLocale/index.js`](diffhunk://#diff-c7bfa99923060ccd8b58a7d57a485849a0ad58957652bafd0001b147ca877abeR55): Introduced a new utility function `flattenEntity` and removed unnecessary console logs. Updated the data parsing logic to use the new utility function. [[1]](diffhunk://#diff-c7bfa99923060ccd8b58a7d57a485849a0ad58957652bafd0001b147ca877abeR55) [[2]](diffhunk://#diff-c7bfa99923060ccd8b58a7d57a485849a0ad58957652bafd0001b147ca877abeL93-L94) [[3]](diffhunk://#diff-c7bfa99923060ccd8b58a7d57a485849a0ad58957652bafd0001b147ca877abeL188-R203)
* …
> fix(direct-translation): nested json fields and dynamic zones

- .github/workflows/unittest.yml
- plugin/__mocks__/initSetup.js
- plugin/server/services/__tests__/untranslated-service.test.js
- plugin/server/services/batch-translate/__tests__/BatchTranslateJob.test.js
- plugin/server/utils/__tests__/dummy-provider.test.js
- providers/libretranslate/lib/__tests__/client.test.js
- providers/libretranslate/lib/__tests__/libretranslate.test.js
re #470 
Fixes warnings in the test cases of the libretranslate provider, due to the async information fetching during initiation and a missing mock query handler.
Also includes some additional test coverage for the main plugin.
> 470 bug missing query handler in unit tests

- plugin/admin/src/components/CMEditViewTranslateLocale/utils/flattenEntity.js
When some components are empty an error was thrown that data is null. This fixes that issue and additionally resets the content of a component if the translation is empty.
fix #472
> fix(direct-translation): errors with empty components

- .github/workflows/e2e.yml
There should be no migration steps necessary, changing the version to v4 should be enough
> ci(e2e workflow): upgrade actions/upload-artifact from v3 to v4

- plugin/server/config/index.js
It is expected by the documentation that blocks are translated by default.
fixes #498
> fix(plugin): update default config to translate blocks

- providers/deepl/README.md
- providers/deepl/lib/__tests__/deepl.test.js
- providers/deepl/lib/index.js
add support for handling multiple glossaries
fixes #500
- Update `providers/deepl/lib/index.js` to handle multiple glossaries from `providerOptions` and select the appropriate glossary based on the source and target locale.
- Add logic to convert source and target language using `parseLocale` function.
- Add a warning log if a glossary is provided in `apiOptions` and overwrite it with the actual glossary to be used for the translation.
- Write tests in `providers/deepl/lib/__tests__/deepl.test.js` to verify that glossaries are handled correctly and that a warning is logged when a glossary is provided in `apiOptions`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/Fekide/strapi-plugin-translate/pull/501?shareId=2d97d358-9c46-4a6f-92f8-5de …
> fix(provider-deepl): glossary handling

- plugin/server/services/translate.js
- plugin/server/utils/__tests__/translatable-fields.test.js
- plugin/server/utils/translatable-fields.js
* **plugin/server/services/translate.js**
- Skip translation if array is empty
* **plugin/server/utils/__tests__/translatable-fields.test.js**
- Add tests to verify that empty or whitespace-only fields are not translated.
* **plugin/server/utils/translatable-fields.js**
- Add check to ignore fields with empty or whitespace-only strings before translation.
fixes #252
> fix(plugin): empty or whitespace-only fields

- plugin/admin/src/components/Collection/CollectionRow.js
- plugin/admin/src/components/Collection/JobStatusBadge.js
cancelling a batch translate job previously lead to an error in the frontend due to a missing optional chaining
fix #521
Issue had been introduced in https://github.com/Fekide/strapi-plugin-translate/commit/8d282ce9e0636c8fcdf369ba4468073282ac29de
> fix(batch-translation): fix frontend error
